export enum GraphQLErrorName {
	BATTERY_NOT_FOUND = 'BATTERY_NOT_FOUND',
	GEO_DATA_NOT_FOUND = 'GEO_DATA_NOT_FOUND',
	HOUSE_NOT_FOUND = 'HOUSE_NOT_FOUND',
	POWER_PLANT_NOT_FOUND = 'POWER_PLANT_NOT_FOUND',
	GENERATORS_NOT_FOUND = 'GENERATORS_NOT_FOUND',
	USER_NOT_FOUND = 'USER_NOT_FOUND',
	PROSUMER_NOT_FOUND = 'PROSUMER_NOT_FOUND',
	MANAGER_NOT_FOUND = 'MANAGER_NOT_FOUND',
	INVALID_RATIO = 'INVALID_RATIO',
	INVALID_USER_TYPE = 'INVALID_USER_TYPE'
}

export enum GraphQLErrorCode {
	BATTERY_NOT_FOUND = 0,
	GEO_DATA_NOT_FOUND = 1,
	HOUSE_NOT_FOUND = 2,
	POWER_PLANT_NOT_FOUND = 3,
	GENERATORS_NOT_FOUND = 4,
	USER_NOT_FOUND = 6,
	PROSUMER_NOT_FOUND = 6,
	MANAGER_NOT_FOUND = 7,
	INVALID_RATIO = 8,
	INVALID_USER_TYPE = 9
}

export const getCode = (message: string): number => {
	return GraphQLErrorCode[<GraphQLErrorName> message];
}
